apiVersion: v1
kind: Pod
metadata:
  name: blobStorage
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: blob-storage
    command: ["/bin/sh", "-c"]
    args:
    - |
      cat <<EOF > /etc/nginx/conf.d/default.conf
      server {
          listen 80;
          server_name localhost;
          
          location / {
              root /usr/share/nginx/html;
              autoindex on;
              autoindex_exact_size off;
              autoindex_localtime on;
          }
      }
      EOF
      nginx -g 'daemon off;'
  volumes:
  - name: blob-storage
    persistentVolumeClaim:
      claimName: blob-storage-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blob-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi