apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets
  namespace: tukano
  labels:
    app: postgres
data:
  POSTGRES_DB: "ps_db"
  POSTGRES_USER: "ps_user"
  POSTGRES_PASSWORD: "SecurePassword"
  POSTGRES_HOST: "postgres.tukano.svc.cluster.local"
  POSTGRES_PORT: "5432"
  DB_NAME: "tukano"
  MINIO_URL: "http://minio-service.tukano:9000"
  # CHANGE THIS AFTER RUNNING
  # minikube service minio-service -n tukano
  # kc edit cm secrets
  # kc delete pod tukano-rest-api-[actualpod]
  MINIO_EXTERNAL_URL: "http://127.0.0.1:63353"
  MINIO_ACCESS_KEY: "minio"
  MINIO_SECRET_KEY: "minio123"
  REDIS_HOST: "redis.tukano.svc.cluster.local"
  REDIS_PASSWORD: "redis123"
  REDIS_PORT: "6379"
  # Apply the external IP ADDRESS of MINIO afterward.