apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: tukano
spec:
  serviceName: redis-cluster-service
  replicas: 3
  selector:
	matchLabels:
  	app: redis-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: redis-namespace
spec:
  type: ClusterIP
  ports:
  - port: 6379
	targetPort: 6379
	name: client
  selector:
	app: redis-cluster
