apiVersion: v1
kind: Service
metadata:
  name: tukano-rest-api
  namespace: tukano
  labels:
    app: tukano-webapp
spec:
  selector:
    app: tukano-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tukano-rest-api-rs
  namespace: tukano
  labels:
    app: tukano-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano-webapp
  template:
    metadata:
      labels:
        app: tukano-webapp
    spec:
      containers:
        - name: tukano-webapp
          image: fdavidfctnova/tukano-webapp
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: secrets
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30